import { describe, it, expect } from 'vitest';
import { execFileSync, spawnSync } from 'child_process';
import { existsSync } from 'fs';
import { join } from 'path';
import { EliumCryptoEngine } from '../src/crypto/elium-crypto';
import { generateRecipientKeypair } from '../src/crypto/recipients';
import { writeEliumPackage, readEliumPackage } from '../src/format/elium-package';
import { createEliumFile } from '../src/format/document';

const WINDOWS_VENV_PYTHON = join(__dirname, '..', '..', '.venv', 'Scripts', 'python.exe');
const PYTHON_CANDIDATES = [
  process.env.PYTHON,
  existsSync(WINDOWS_VENV_PYTHON) ? WINDOWS_VENV_PYTHON : undefined,
  'python3',
  'python',
].filter((candidate): candidate is string => Boolean(candidate));
const PYTHON_EXEC = PYTHON_CANDIDATES.find(
  (candidate) => spawnSync(candidate, ['--version'], { stdio: 'ignore' }).status === 0,
);
const HELPER_SCRIPT = join(__dirname, '..', '..', 'tests', 'python', 'interop_helper.py');
const hasPython = Boolean(PYTHON_EXEC);

// Requires the local Python venv; skipped otherwise (e.g. Linux CI).
describe.skipIf(!hasPython)('Cross-Platform Interoperability (Python <-> Web)', () => {
  it('should decode a container generated by Python (cascade=false)', async () => {
    const payloadStr = 'Hello from Python! This is an interop test without cascade.';
    const password = 'interop_password_123';
    
    // Call python to encode
    const blob = execFileSync(PYTHON_EXEC, [HELPER_SCRIPT, 'encode', password, 'false'], {
      input: payloadStr
    });
    
    // Decode in Web
    const { payload, header, manifest } = await EliumCryptoEngine.decodeContainer(new Uint8Array(blob), password);
    const decodedText = new TextDecoder().decode(payload);
    
    expect(decodedText).toBe(payloadStr);
    expect(header.version).toBe(3);
    expect(header.crypto.cascade).toBeNull();
    expect(manifest.files[0].name).toBe('interop.txt');
  });

  it('should decode a container generated by Python (cascade=true)', async () => {
    const payloadStr = 'Hello from Python! This is an interop test WITH CASCADE ChaCha20.';
    const password = 'interop_password_cascade';
    
    // Call python to encode
    const blob = execFileSync(PYTHON_EXEC, [HELPER_SCRIPT, 'encode', password, 'true'], {
      input: payloadStr
    });
    
    // Decode in Web
    const { payload, header } = await EliumCryptoEngine.decodeContainer(new Uint8Array(blob), password);
    const decodedText = new TextDecoder().decode(payload);
    
    expect(decodedText).toBe(payloadStr);
    expect(header.crypto.cascade).toBe('chacha20-poly1305');
  });

  it('should encode a container in Web and decode it in Python', async () => {
    const payloadStr = 'Hello from Web! This should be readable by Python.';
    const password = 'web_password_to_python';
    const payload = new TextEncoder().encode(payloadStr);
    
    // Encode in Web
    const encoded = await EliumCryptoEngine.encodeContainer(payload, password, 'web.txt');
    
    // Call python to decode
    const resultJson = execFileSync(PYTHON_EXEC, [HELPER_SCRIPT, 'decode', password], {
      input: Buffer.from(encoded),
      encoding: 'utf-8'
    });
    
    const result = JSON.parse(resultJson);
    const decodedText = Buffer.from(result.payload_b64, 'base64').toString('utf-8');

    expect(decodedText).toBe(payloadStr);
    expect(result.header.version).toBe(3);
    expect(result.manifest.files[0].name).toBe('web.txt');
  });

  // --- Multi-recipient .elium PACKAGE interop (both directions) -------------
  it('Python writes a multi-recipient .elium that Web opens with the private key', async () => {
    const { privateHex, publicHex } = await generateRecipientKeypair();
    const text = 'Paquet multi-destinataires Python -> Web';
    const blob = execFileSync(PYTHON_EXEC!, [HELPER_SCRIPT, 'doc-encode-recipients', 'encrypted', publicHex], { input: text });
    const r = await readEliumPackage(new Uint8Array(blob), { recipientKey: { privateHex, publicHex } });
    expect(JSON.stringify(r.file.document)).toContain(text);
    expect(r.file.manifest.protection.recipients?.length).toBe(1);
  });

  it('Web writes a multi-recipient .elium that Python opens with the private key', async () => {
    const { privateHex, publicHex } = await generateRecipientKeypair();
    const doc = {
      type: 'doc',
      content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Paquet Web -> Python' }] }],
    } as unknown as Parameters<typeof createEliumFile>[0]['doc'];
    const file = await createEliumFile({ title: 'Interop recip', profile: 'encrypted', doc });
    const bytes = await writeEliumPackage(file, { recipients: [publicHex] });
    const resultJson = execFileSync(PYTHON_EXEC!, [HELPER_SCRIPT, 'doc-decode-recipient', privateHex], {
      input: Buffer.from(bytes),
      encoding: 'utf-8',
    });
    const result = JSON.parse(resultJson);
    expect(result.manifest.title).toBe('Interop recip');
    expect(result.text).toContain('Paquet Web -> Python');
    expect(result.recipients.length).toBe(1);
  });
});
