// Must be the very first import — see pdfjs-node-shim.ts for why.
import "./pdfjs-node-shim";
import { createRequire } from "node:module";
import { readFileSync } from "node:fs";
import { pathToFileURL } from "node:url";
import { describe, expect, it } from "vitest";
import * as pdfjsLib from "pdfjs-dist";
import { PdfEngine } from "../src/pdf/core/engine";
import { buildRuns, groupLines, type TextBlock, type TextLine } from "../src/pdf/core/text";
import type { ContentEdit, TextSpan } from "../src/pdf/model/types";
import { readTextBlocks } from "../src/pdf/ops/textblocks";
import { rewrittenPage } from "../src/pdf/ops/editpreview";

pdfjsLib.GlobalWorkerOptions.workerSrc = pathToFileURL(
  createRequire(import.meta.url).resolve("pdfjs-dist/build/pdf.worker.min.mjs"),
).href;

/**
 * The « Modifier le texte » engine on a corpus of real-world PDFs
 * (tests/fixtures/textedit, regenerated by tests/support/textedit-fixtures.*):
 * LibreOffice (Word / PowerPoint), pdf-lib (Standard 14, CID), Chromium, a
 * Form XObject. Every detected paragraph of every page is edited.
 */

const FIXTURES = ["letter", "slides", "form-xobject", "pdflib", "chromium"] as const;
const bytesOf = (name: string) => new Uint8Array(readFileSync(`tests/fixtures/textedit/${name}.pdf`));

const sources = new Map<string, { bytes: Uint8Array; engine: PdfEngine }>();
async function open(name: string) {
  let s = sources.get(name);
  if (!s) {
    const bytes = bytesOf(name);
    s = { bytes, engine: await PdfEngine.open(bytes.slice()) };
    sources.set(name, s);
  }
  return s;
}

async function blocksOf(name: string, page: number): Promise<TextBlock[]> {
  const { bytes, engine } = await open(name);
  return readTextBlocks(engine, { bytes }, page);
}

/** pdf.js' view of a one-page PDF: its lines and its whole text. */
async function lookAt(bytes: Uint8Array): Promise<{ lines: TextLine[]; text: string; blocks: TextBlock[] }> {
  const engine = await PdfEngine.open(bytes.slice());
  const page = await engine.page(0);
  const vp = page.getViewport({ scale: 1, rotation: 0 });
  const [tc, fonts] = await Promise.all([engine.text(0), engine.fonts(0)]);
  const lines = groupLines(buildRuns(tc, vp.transform as unknown as number[], fonts), tc.items);
  const blocks = await readTextBlocks(engine, { bytes }, 0);
  const text = (tc.items as { str?: string }[]).map((i) => i.str ?? "").join("");
  return { lines, text, blocks };
}

const NORM = (s: string) => s.normalize("NFKC").replace(/\s+/g, "");
const flat = (s: string) => s.replace(/\s+/g, " ").trim();

/** Characters of `a` minus those of `b` (a multiset difference), sorted, as a string. */
function bag(s: string): Map<string, number> {
  const m = new Map<string, number>();
  for (const ch of NORM(s)) m.set(ch, (m.get(ch) ?? 0) + 1);
  return m;
}
function sameBag(a: Map<string, number>, b: Map<string, number>): string[] {
  const diff: string[] = [];
  for (const k of new Set([...a.keys(), ...b.keys()])) {
    const d = (a.get(k) ?? 0) - (b.get(k) ?? 0);
    if (d) diff.push(`${k}:${d > 0 ? "+" : ""}${d}`);
  }
  return diff;
}

function editOf(b: TextBlock, spans: TextSpan[], extra: Partial<ContentEdit> = {}): ContentEdit {
  return {
    id: `e-${b.key}`,
    pageId: "p",
    blockKey: b.key,
    original: b.text,
    text: spans.map((s) => s.text).join(""),
    rect: b.rect,
    fontSize: b.fontSize,
    leading: b.leading,
    align: b.align,
    fontFamily: b.fontFamily,
    bold: b.bold,
    italic: b.italic,
    spans,
    indent: b.indent,
    ...extra,
  };
}

/** The block with " AJOUT" typed at its end (in the style of its last span). */
function appended(b: TextBlock): TextSpan[] {
  const spans = b.spans!.map((s) => ({ ...s }));
  spans[spans.length - 1] = { ...spans[spans.length - 1], text: spans[spans.length - 1].text + " AJOUT" };
  return spans;
}

/** The block with its longest word (≥ 4 letters, in a span of its own style) replaced by « REMPLACÉ ». */
function changed(b: TextBlock): { spans: TextSpan[]; word: string } | null {
  let best: { si: number; word: string; at: number } | null = null;
  b.spans!.forEach((s, si) => {
    const re = /\p{L}{4,}/gu;
    let m: RegExpExecArray | null;
    while ((m = re.exec(s.text)) !== null)
      if (!best || m[0].length > best.word.length) best = { si, word: m[0], at: m.index };
  });
  if (!best) return null;
  const { si, word, at } = best as { si: number; word: string; at: number };
  const spans = b.spans!.map((s) => ({ ...s }));
  spans[si] = { ...spans[si], text: spans[si].text.slice(0, at) + "REMPLACÉ" + spans[si].text.slice(at + word.length) };
  return { spans, word };
}

describe("text edit engine — detection on the corpus", () => {
  it("joins wrapped lines, keeps hard breaks (address, list items, table columns)", async () => {
    const letter = await blocksOf("letter", 0);
    const find = (start: string) => letter.find((b) => b.text.startsWith(start))!;
    expect(find("Société Exemple").text).toBe("Société Exemple SARL\n12 rue de la Paix\n75002 Paris");
    // A justified paragraph of 4 lines with a first-line indent: one line of text.
    const just = find("Le présent document");
    expect(just.lines.length).toBeGreaterThan(2);
    expect(just.text).not.toContain("\n");
    expect(just.align).toBe("justify");
    expect(just.indent!.first).toBeGreaterThan(20);
    expect(just.indent!.rest).toBeLessThan(1);
    // List items: one per line, each item's own wrapped lines joined.
    const items = find("Une première étape");
    expect(items.text.split("\n")).toHaveLength(3);
    expect(find("1. Signature").text.split("\n")).toHaveLength(2);
    // Single lines placed by alignment.
    expect(find("Paris, le 3 octobre").align).toBe("right");
    expect(find("Objet : proposition").align).toBe("center");
    expect(find("Pied de page").align).toBe("center");
    // Table columns: cells stay apart.
    expect(find("Chaise").text).toBe("Chaise\nBureau");

    // Two columns on page 2: each paragraph its own block, all wrapped lines joined.
    const cols = await blocksOf("letter", 1);
    const paras = cols.filter((b) => b.text.startsWith("Colonne, paragraphe"));
    expect(paras).toHaveLength(4);
    for (const p of paras) expect(p.text).not.toContain("\n");
    expect(new Set(paras.map((p) => Math.round(p.rect.x))).size).toBe(2);

    const chrome = await blocksOf("chromium", 0);
    expect(chrome.find((b) => b.text.startsWith("Colonne gauche"))!.text).not.toContain("\n");
    expect(chrome.find((b) => b.text.startsWith("Colonne droite"))!.text).not.toContain("\n");
    const slides = await blocksOf("slides", 0);
    expect(slides.find((b) => b.text.startsWith("Les objectifs"))!.text).toBe(
      "Les objectifs du trimestre ont été atteints dans les délais prévus par le plan de charge.\nLe budget reste maîtrisé.",
    );
  });

  it("spans carry the content stream's font resource and colour; bold and coloured words are their own spans", async () => {
    for (const [name, start] of [
      ["letter", "Nous attirons"],
      ["chromium", "Second paragraphe"],
    ] as const) {
      const b = (await blocksOf(name, 0)).find((x) => x.text.startsWith(start))!;
      const spans = b.spans!;
      expect(spans.map((s) => s.text).join("")).toBe(b.text);
      const bold = spans.find((s) => s.style.bold)!;
      expect(bold.text.trim()).toMatch(/^(important|gras)$/);
      expect(bold.style.fontName).toMatch(/Bold/);
      const red = spans.find((s) => s.style.color === "#c00000")!;
      expect(red.text.trim()).toBe("rouge");
      const plain = spans.filter((s) => !s.style.bold && s.style.color === "#000000");
      expect(plain.length).toBeGreaterThan(1);
      for (const s of spans) expect(s.style.fontResource).toBeTruthy();
      expect(new Set(plain.map((s) => s.style.fontResource)).size).toBe(1);
    }
    // Header in grey, a slide title in its theme colour, text inside a form XObject.
    expect((await blocksOf("letter", 0))[0].spans![0].style.color).toBe("#555555");
    expect((await blocksOf("slides", 0))[0].spans![0].style.color).toBe("#1f3864");
    const form = await blocksOf("form-xobject", 0);
    expect(form[0].spans![0].style.fontResource).toMatch(/^Fm0\//);
  });

  it("every block of every page: spans concatenate to the text", async () => {
    for (const name of FIXTURES) {
      const { engine } = await open(name);
      for (let p = 0; p < engine.pageCount; p++) {
        for (const b of await blocksOf(name, p)) {
          expect(b.spans!.map((s) => s.text).join("")).toBe(b.text);
          expect(b.spans!.every((s) => /^#[0-9a-f]{6}$/.test(s.style.color))).toBe(true);
        }
      }
    }
  });
});

describe("text edit engine — editing every block of the corpus", () => {
  for (const name of FIXTURES) {
    it(`${name}: append a word / change a word, nothing else moves, nothing doubles`, async () => {
      const { bytes, engine } = await open(name);
      for (let p = 0; p < engine.pageCount; p++) {
        const blocks = await blocksOf(name, p);
        const before = await lookAt((await rewrittenPage(bytes, null, p, [])).bytes);
        for (const b of blocks) {
          // A column of bullets alone (no letter, no digit) is not edited as text.
          if (!/[\p{L}\p{N}]/u.test(b.text)) continue;
          const variants: { spans: TextSpan[]; label: string }[] = [{ spans: appended(b), label: "append" }];
          const c = changed(b);
          if (c) variants.push({ spans: c.spans, label: `change ${c.word}` });
          for (const v of variants) {
            const edit = editOf(b, v.spans);
            const r = await rewrittenPage(bytes, null, p, [edit]);
            const where = `${name} p${p} ${b.key} ${v.label}`;
            expect(r.skipped, where).toBe(0);
            const after = await lookAt(r.bytes);
            // Exactly the original's characters out, the new ones in.
            const expected = bag(before.text);
            for (const [k, n] of bag(b.text)) expected.set(k, (expected.get(k) ?? 0) - n);
            for (const [k, n] of bag(edit.text)) expected.set(k, (expected.get(k) ?? 0) + n);
            expect(sameBag(bag(after.text), expected), where).toEqual([]);
            expect(NORM(after.text), where).toContain(NORM(edit.text).slice(-12));
            // Every other paragraph is still there, word for word.
            const out = new Set(after.blocks.map((x) => NORM(x.text)));
            const outAll = NORM(after.blocks.map((x) => x.text).join(""));
            // (Text a longer paragraph grows over — the two lines under it — may mix with it in pdf.js'
            // reading: the character count above already proves nothing was lost or doubled there.)
            const grow = {
              x0: b.rect.x,
              x1: b.rect.x + b.rect.w,
              y0: b.rect.y,
              y1: b.rect.y + b.rect.h + 2.2 * b.leading,
            };
            for (const o of blocks) {
              if (o === b || !NORM(o.text)) continue;
              const inBand =
                o.rect.x < grow.x1 &&
                o.rect.x + o.rect.w > grow.x0 &&
                o.rect.y < grow.y1 &&
                o.rect.y + o.rect.h > grow.y0;
              if (inBand) continue;
              if (!out.has(NORM(o.text)))
                expect(outAll, `${where}: ${o.key} « ${flat(o.text)} »`).toContain(NORM(o.text));
            }
          }
        }
      }
    }, 120_000);
  }
});

describe("text edit engine — fidelity", () => {
  it("re-laying out an unchanged paragraph puts back its line breaks and baselines (±1.5 pt)", async () => {
    let checked = 0;
    for (const name of FIXTURES) {
      const { bytes, engine } = await open(name);
      for (let p = 0; p < engine.pageCount; p++) {
        for (const b of await blocksOf(name, p)) {
          if (!/\p{L}/u.test(b.text) || Math.abs(b.lines[0].angle) > 0.01) continue;
          const r = await rewrittenPage(bytes, null, p, [editOf(b, b.spans!)]);
          const after = await lookAt(r.bytes);
          const where = `${name} p${p} ${b.key} « ${flat(b.text).slice(0, 40)} »`;
          const near = (l: TextLine) =>
            l.origin.y > b.rect.y - 2 &&
            l.origin.y < b.rect.y + b.rect.h + 2 &&
            l.rect.x > b.rect.x - 3 &&
            l.rect.x < b.rect.x + b.rect.w;
          const got = after.lines.filter(near);
          expect(
            got.map((l) => NORM(l.text)),
            where,
          ).toEqual(b.lines.map((l) => NORM(l.text)));
          got.forEach((l, i) => {
            const o = b.lines[i];
            expect(Math.abs(l.origin.y - o.origin.y), `${where} line ${i} baseline`).toBeLessThan(1.5);
            if (b.align === "left" || b.align === "justify")
              expect(Math.abs(l.rect.x - o.rect.x), `${where} line ${i} start`).toBeLessThan(1.5);
            if (b.align === "right" || (b.align === "justify" && b.soft?.[i]))
              expect(Math.abs(l.rect.x + l.rect.w - (o.rect.x + o.rect.w)), `${where} line ${i} end`).toBeLessThan(1.5);
          });
          checked++;
        }
      }
    }
    expect(checked).toBeGreaterThan(30);
  }, 120_000);

  it("a bold word stays bold, a red word red, when another word of the paragraph is edited", async () => {
    for (const [name, start] of [
      ["letter", "Nous attirons"],
      ["chromium", "Second paragraphe"],
    ] as const) {
      const { bytes } = await open(name);
      const b = (await blocksOf(name, 0)).find((x) => x.text.startsWith(start))!;
      const spans = b.spans!.map((s, i) => (i === 0 ? { ...s, text: s.text.replace(/^\S+/, "Désormais, nous") } : s));
      const r = await rewrittenPage(bytes, null, 0, [editOf(b, spans)]);
      const out = (await lookAt(r.bytes)).blocks.find((x) => x.text.startsWith("Désormais"))!;
      expect(out, name).toBeTruthy();
      expect(out.spans!.find((s) => s.style.bold)!.text.trim()).toBe(b.spans!.find((s) => s.style.bold)!.text.trim());
      expect(out.spans!.find((s) => s.style.color === "#c00000")!.text.trim()).toBe("rouge");
      // Still set in the paragraph's own fonts (no substitution).
      const names = new Set(out.spans!.map((s) => s.style.fontName));
      for (const s of b.spans!) expect(names.has(s.style.fontName), `${name} ${s.style.fontName}`).toBe(true);
    }
  });

  it("a word the subset font lacks is set in a substitute face, that word only", async () => {
    const { bytes } = await open("pdflib");
    const b = (await blocksOf("pdflib", 1)).find((x) => x.text.startsWith("Ce paragraphe"))!;
    const spans = [{ ...b.spans![0], text: b.spans![0].text.replace("Ce paragraphe", "Ce Ωmega paragraphe") }];
    const r = await rewrittenPage(bytes, null, 1, [editOf(b, spans)]);
    const out = (await lookAt(r.bytes)).blocks.find((x) => x.text.includes("Ωmega"))!;
    expect(out.text).toBe(spans[0].text);
    const own = out.spans!.filter((s) => s.style.fontName === b.spans![0].style.fontName);
    // Everything but the new word keeps the original CID font.
    expect(own.map((s) => s.text).join("").length).toBeGreaterThan(out.text.length - 10);
  });
});

describe("text edit engine — safety", () => {
  it("text inside a form XObject drawn by two pages: edited on one page only", async () => {
    const { PDFDocument } = await import("pdf-lib");
    const { pageFrame } = await import("../src/pdf/ops/annots-pdf");
    const { FontBook } = await import("../src/pdf/ops/fonts");
    const { applyTextEdits } = await import("../src/pdf/ops/textedit");
    const { bytes } = await open("form-xobject");
    const b = (await blocksOf("form-xobject", 0)).find((x) => x.text.startsWith("Le présent"))!;
    const doc = await PDFDocument.load(bytes);
    const page = doc.getPage(0);
    const r = await applyTextEdits(doc, page, [editOf(b, appended(b))], pageFrame(page), new FontBook(doc));
    // (« AJOUT »'s capitals are not in the subset font: that word is substituted.)
    expect(r.skipped).toBe(0);
    expect(r.native + r.substituted).toBe(1);
    const out = await doc.save();
    const all = await PdfEngine.open(out.slice());
    const text = async (i: number) =>
      ((await all.text(i)).items as { str?: string }[]).map((x) => x.str ?? "").join("");
    expect(NORM(await text(0))).toContain(NORM(b.text + " AJOUT"));
    expect(NORM(await text(0)).split(NORM("Le présent document")).length).toBe(2);
    // Page 2 draws the same form: untouched.
    expect(NORM(await text(1))).toContain(NORM(b.text));
    expect(NORM(await text(1))).not.toContain("AJOUT");
  });

  it("a block that is no longer there is skipped, and nothing is drawn", async () => {
    const { bytes } = await open("letter");
    const b = (await blocksOf("letter", 0)).find((x) => x.text.startsWith("Veuillez"))!;
    const ghost = editOf(b, [{ ...b.spans![0], text: "Texte fantôme" }], {
      original: "Un paragraphe qui n'existe pas du tout sur cette page",
    });
    const r = await rewrittenPage(bytes, null, 0, [ghost]);
    expect(r.skipped).toBe(1);
    const after = await lookAt(r.bytes);
    expect(after.text).not.toContain("fantôme");
    expect(NORM(after.text)).toContain(NORM(b.text));
    // Elsewhere on the page: nothing there at all.
    const empty = editOf(b, [{ ...b.spans![0], text: "Rien" }], { rect: { x: 300, y: 600, w: 100, h: 20 } });
    expect((await rewrittenPage(bytes, null, 0, [empty])).skipped).toBe(1);
  });

  it("deleting a paragraph removes exactly it (the preview's « paragraph being typed »)", async () => {
    const { bytes } = await open("chromium");
    const blocks = await blocksOf("chromium", 0);
    const b = blocks.find((x) => x.text.startsWith("Colonne gauche"))!;
    const t0 = performance.now();
    const r = await rewrittenPage(bytes, null, 0, [editOf(b, b.spans!, { deleted: true, text: "" })]);
    const ms = performance.now() - t0;
    const after = await lookAt(r.bytes);
    expect(NORM(after.text)).not.toContain(NORM("Colonne gauche"));
    for (const o of blocks) if (o !== b) expect(NORM(after.text)).toContain(NORM(o.text));
    expect(ms).toBeLessThan(400);
  });

  it("old edits (no spans) still work: the block's own font, colour and size", async () => {
    const { bytes } = await open("letter");
    const b = (await blocksOf("letter", 0)).find((x) => x.text.startsWith("Le présent"))!;
    const { spans: _s, indent: _i, ...old } = editOf(b, b.spans!, { text: "Le document décrit les parties." });
    void _s;
    void _i;
    const r = await rewrittenPage(bytes, null, 0, [old]);
    const out = (await lookAt(r.bytes)).blocks.find((x) => x.text.startsWith("Le document décrit les parties"))!;
    expect(out.spans![0].style.fontName).toBe(b.spans![0].style.fontName);
  });
});

describe("text edit engine — speed", () => {
  it("blocks of a 300-word page in < 300 ms, a preview in < 400 ms", async () => {
    const bytes = bytesOf("letter");
    const engine = await PdfEngine.open(bytes.slice());
    await engine.text(0);
    await engine.fonts(0);
    const t0 = performance.now();
    const blocks = await readTextBlocks(engine, { bytes }, 0);
    const t1 = performance.now();
    await readTextBlocks(engine, { bytes }, 0);
    const t2 = performance.now();
    expect(blocks.length).toBeGreaterThan(10);
    expect(t1 - t0).toBeLessThan(300);
    expect(t2 - t1).toBeLessThan(5);
    const b = blocks.find((x) => x.text.startsWith("Nous attirons"))!;
    await rewrittenPage(bytes, null, 0, [editOf(b, appended(b))]);
    const t3 = performance.now();
    await rewrittenPage(bytes, null, 0, [editOf(b, appended(b))]);
    expect(performance.now() - t3).toBeLessThan(400);
  });
});

describe("text edit engine — page geometry, colours, layout rules", () => {
  /** A page of the pdf-lib fixture turned (/Rotate 90) and cropped (CropBox off the origin). */
  async function turnedAndCropped(): Promise<Uint8Array> {
    const { PDFDocument, degrees } = await import("pdf-lib");
    const doc = await PDFDocument.load(bytesOf("pdflib"));
    const page = doc.getPage(0);
    page.setRotation(degrees(90));
    page.setCropBox(40, 100, 500, 720);
    doc.removePage(1);
    return doc.save();
  }

  it("a rotated, cropped page: blocks, edit and re-layout in place", async () => {
    const bytes = await turnedAndCropped();
    const engine = await PdfEngine.open(bytes.slice());
    const blocks = await readTextBlocks(engine, { bytes }, 0);
    const b = blocks.find((x) => x.text.startsWith("Ce paragraphe est composé en Helvetica"))!;
    expect(b.text).not.toContain("\n");
    const same = await rewrittenPage(bytes, null, 0, [editOf(b, b.spans!)]);
    const after = await lookAt(same.bytes);
    const lines = after.lines.filter((l) => l.origin.y > b.rect.y && l.origin.y < b.rect.y + b.rect.h + 2);
    expect(lines.map((l) => NORM(l.text))).toEqual(b.lines.map((l) => NORM(l.text)));
    lines.forEach((l, i) => {
      expect(Math.abs(l.origin.y - b.lines[i].origin.y)).toBeLessThan(1.5);
      expect(Math.abs(l.rect.x - b.lines[i].rect.x)).toBeLessThan(1.5);
    });
    const r = await rewrittenPage(bytes, null, 0, [editOf(b, appended(b))]);
    expect(r.skipped).toBe(0);
    expect(NORM((await lookAt(r.bytes)).text)).toContain(NORM(b.text + " AJOUT"));
  });

  it("hard line breaks and indents are honoured; justified lines reach the right edge", async () => {
    const { bytes } = await open("letter");
    const b = (await blocksOf("letter", 0)).find((x) => x.text.startsWith("Le présent"))!;
    const text =
      "Premier alinéa, assez long pour occuper plus d'une ligne entière de la page quand il est composé en justifié avec un retrait.\nSecond alinéa.";
    const r = await rewrittenPage(bytes, null, 0, [editOf(b, [{ ...b.spans![0], text }])]);
    const after = await lookAt(r.bytes);
    const lines = after.lines.filter((l) => l.origin.y > b.rect.y && l.origin.y < b.rect.y + b.rect.h + 2);
    expect(lines.map((l) => NORM(l.text)).join("")).toBe(NORM(text));
    expect(lines.length).toBe(3);
    // First line indented, the wrapped one not, the hard-broken one indented again.
    expect(lines[0].rect.x - b.rect.x).toBeCloseTo(b.indent!.first, 0);
    expect(lines[1].rect.x - b.rect.x).toBeLessThan(1);
    expect(lines[2].rect.x - b.rect.x).toBeCloseTo(b.indent!.first, 0);
    // The wrapped (justified) line ends at the column's right edge; the last ones do not.
    expect(Math.abs(lines[0].rect.x + lines[0].rect.w - (b.rect.x + b.rect.w))).toBeLessThan(1.5);
    expect(lines[1].rect.x + lines[1].rect.w).toBeLessThan(b.rect.x + b.rect.w - 20);
  });

  it("reads the fill colour through gray, RGB, CMYK, ICC and Separation spaces", async () => {
    const { PDFDocument, StandardFonts, PDFName } = await import("pdf-lib");
    const doc = await PDFDocument.create();
    const font = await doc.embedFont(StandardFonts.Helvetica);
    const page = doc.addPage([400, 400]);
    page.drawText("x", { x: 10, y: 10, size: 10, font });
    const fontName = Array.from(
      (page.node.Resources()!.lookup(PDFName.of("Font")) as import("pdf-lib").PDFDict).keys(),
    )[0].asString();
    const icc = doc.context.register(doc.context.flateStream(new Uint8Array(4), { N: 3 } as never));
    const tint = doc.context.obj({ FunctionType: 2, Domain: [0, 1], C0: [0, 0, 0, 0], C1: [0, 1, 1, 0], N: 1 });
    page.node.Resources()!.set(
      PDFName.of("ColorSpace"),
      doc.context.obj({
        CsI: [PDFName.of("ICCBased"), icc],
        CsS: [PDFName.of("Separation"), PDFName.of("Red"), PDFName.of("DeviceCMYK"), tint],
      }),
    );
    const lines = [
      ["0.5 g", "Gris"],
      ["0 0 1 rg", "Bleu"],
      ["0 1 1 0 k", "Rouge"],
      ["/CsI cs 0 0.5 0 sc", "Vert"],
      ["/CsS cs 1 scn", "Separation"],
    ];
    const ops = lines
      .map(([c, t], i) => `BT ${fontName} 12 Tf ${c} 1 0 0 1 20 ${360 - i * 30} Tm (${t}) Tj ET`)
      .join("\n");
    page.node.set(PDFName.of("Contents"), doc.context.register(doc.context.flateStream(new TextEncoder().encode(ops))));
    const bytes = await doc.save();
    const engine = await PdfEngine.open(bytes.slice());
    const blocks = await readTextBlocks(engine, { bytes }, 0);
    const colour = (t: string) => blocks.find((b) => b.text === t)!.spans![0].style.color;
    expect(colour("Gris")).toBe("#808080");
    expect(colour("Bleu")).toBe("#0000ff");
    expect(colour("Rouge")).toBe("#ff0000");
    expect(colour("Vert")).toBe("#008000");
    expect(colour("Separation")).toBe("#ff0000");
  });
});

describe("text edit engine — underline", () => {
  it("an underlined line is read as underlined; editing it draws the rule anew, the old one goes", async () => {
    const { PDFDocument, StandardFonts, rgb } = await import("pdf-lib");
    const { scanPage } = await import("../src/pdf/ops/textblocks");
    const doc = await PDFDocument.create();
    const font = await doc.embedFont(StandardFonts.Helvetica);
    const page = doc.addPage([400, 400]);
    const t = "Texte souligné ici";
    page.drawText(t, { x: 60, y: 300, size: 12, font });
    // (A little longer than pdf-lib's own measure of the line, which falls short of what it draws.)
    page.drawRectangle({ x: 60, y: 298, width: font.widthOfTextAtSize(t, 12) + 3, height: 0.6, color: rgb(0, 0, 0) });
    page.drawText("Autre ligne sans trait", { x: 60, y: 250, size: 12, font });
    const bytes = await doc.save();
    const engine = await PdfEngine.open(bytes.slice());
    const blocks = await readTextBlocks(engine, { bytes }, 0);
    const b = blocks.find((x) => x.text === t)!;
    expect(b.spans![0].style.underline).toBe(true);
    expect(blocks.find((x) => x.text.startsWith("Autre"))!.spans![0].style.underline).toBeFalsy();
    const r = await rewrittenPage(bytes, null, 0, [editOf(b, appended(b))]);
    const out = await PDFDocument.load(r.bytes);
    const scan = await scanPage(out.getPage(0));
    // The old rule is gone; each new line has its own (the box wraps « AJOUT » to a second line).
    const after2 = await lookAt(r.bytes);
    const lines = after2.lines.filter((l) => l.text.startsWith("Texte") || l.text === "AJOUT");
    expect(scan.rules).toHaveLength(lines.length);
    for (const l of lines) {
      const rule = scan.rules.find((x) => Math.abs(400 - x.box.y1 - l.origin.y) < 4)!;
      expect(Math.abs(rule.box.x1 - rule.box.x0 - l.rect.w)).toBeLessThan(1);
    }
    const after = (await lookAt(r.bytes)).blocks.find((x) => x.text.startsWith(t))!;
    expect(after.spans![0].style.underline).toBe(true);
  });
});

describe("text edit engine — justified or not", () => {
  /** The operators drawn by the rewritten paragraph (after the engine's `0 Tc` reset). */
  async function newOps(bytes: Uint8Array): Promise<{ shows: string[]; tw: number[] }> {
    const { PDFDocument } = await import("pdf-lib");
    const { parseContentStream } = await import("../src/pdf/core/contentstream");
    const { readPageContentBytes } = await import("../src/pdf/ops/content");
    const doc = await PDFDocument.load(bytes);
    const ops = parseContentStream(readPageContentBytes(doc.getPage(0)));
    const tail = ops.slice(ops.map((o) => o.op).lastIndexOf("Tc"));
    return {
      shows: tail.filter((o) => o.op === "Tj" || o.op === "TJ").map((o) => o.op),
      tw: tail.filter((o) => o.op === "Tw").map((o) => (o.args[0]?.t === "num" ? o.args[0].v : NaN)),
    };
  }

  /** pdf.js' text items of the (one-page) output lying on the lines of `b` (and `extra` lines below). */
  async function itemsOn(bytes: Uint8Array, b: TextBlock, extra = 1): Promise<string[]> {
    const engine = await PdfEngine.open(bytes.slice());
    const vp = (await engine.page(0)).getViewport({ scale: 1, rotation: 0 });
    const tc = await engine.text(0);
    return (tc.items as { str?: string; transform?: number[] }[])
      .filter((i) => {
        if (!i.str?.trim() || !i.transform) return false;
        const y = vp.transform[3] * i.transform[5] + vp.transform[5];
        return y > b.rect.y && y < b.rect.y + b.rect.h + extra * b.leading;
      })
      .map((i) => i.str!);
  }

  const singleSpaces = (items: string[]) => {
    for (const s of items) expect(s, JSON.stringify(items)).not.toMatch(/\s{2,}/);
  };

  it("a ragged paragraph whose wrapped lines end alike stays left, and reads one clean string per line", async () => {
    const { bytes } = await open("pdflib");
    const b = (await blocksOf("pdflib", 2)).find((x) => x.text.startsWith("Premier paragraphe"))!;
    expect(b.lines.length).toBe(3);
    // Lines 1 and 2 end at the same place (what made it read as justified)…
    expect(Math.abs(b.lines[0].rect.x + b.lines[0].rect.w - (b.lines[1].rect.x + b.lines[1].rect.w))).toBeLessThan(1);
    expect(b.text).not.toContain("\n");
    // …but its word gaps are natural spaces: left-aligned.
    expect(b.align).toBe("left");
    const spans = [{ ...b.spans![0], text: b.text + " Fin ajoutée." }];
    const r = await rewrittenPage(bytes, null, 2, [editOf(b, spans)]);
    const items = await itemsOn(r.bytes, b);
    singleSpaces(items);
    expect(
      items.some((i) => i.includes("enfin. Fin ajoutée.")),
      JSON.stringify(items),
    ).toBe(true);
    // One string per line, no word-by-word pieces.
    expect(items.length).toBeLessThanOrEqual(b.lines.length + 1);
    const { shows, tw } = await newOps(r.bytes);
    expect(shows.length).toBeLessThanOrEqual(b.lines.length + 1);
    expect(tw.every((v) => v === 0)).toBe(true);
  });

  it("words typed in letters the subset font lacks stay one string with single spaces (one face, spaces included)", async () => {
    const { bytes } = await open("chromium");
    const b = (await blocksOf("chromium", 0)).find((x) => x.text.startsWith("Premier paragraphe"))!;
    const spans = [{ ...b.spans![0], text: b.text + " Fin JWQ ajoutée." }];
    const r = await rewrittenPage(bytes, null, 0, [editOf(b, spans)]);
    const items = await itemsOn(r.bytes, b, 2);
    singleSpaces(items);
    (await import("node:fs")).writeFileSync("/tmp/items.json", JSON.stringify(items));
    // One item (a face change would cut it into « Fin » « JWQ » « ajoutée. »).
    expect(
      items.some((i) => i.includes("Fin JWQ ajoutée.")),
      JSON.stringify(items),
    ).toBe(true);
  });

  it("a really justified paragraph (spaces are code 32) is set with Tw: one show per line, clean text", async () => {
    const { bytes } = await open("pdflib");
    const b = (await blocksOf("pdflib", 2)).find((x) => x.text.startsWith("Ce paragraphe est réellement"))!;
    expect(b.align).toBe("justify");
    const r = await rewrittenPage(bytes, null, 2, [editOf(b, appended(b))]);
    const { shows, tw } = await newOps(r.bytes);
    expect(shows.every((o) => o === "Tj")).toBe(true);
    expect(tw.some((v) => v > 0.1)).toBe(true);
    // Reset for the last line (and anything after).
    expect(tw[tw.length - 1]).toBe(0);
    const items = await itemsOn(r.bytes, b, 2);
    singleSpaces(items);
    expect(NORM(items.join(""))).toBe(NORM(b.text + " AJOUT"));
    const after = await lookAt(r.bytes);
    const lines = after.lines.filter((l) => l.origin.y > b.rect.y && l.origin.y < b.rect.y + b.rect.h + 2 * b.leading);
    expect(lines.length).toBeGreaterThan(1);
    for (const l of lines.slice(0, -1)) expect(Math.abs(l.rect.x + l.rect.w - (b.rect.x + b.rect.w))).toBeLessThan(1.5);
  });

  it("a justified LibreOffice paragraph (its subset font's space is not code 32): one TJ per line, clean text", async () => {
    const { bytes } = await open("letter");
    const b = (await blocksOf("letter", 0)).find((x) => x.text.startsWith("Le présent"))!;
    expect(b.align).toBe("justify");
    const r = await rewrittenPage(bytes, null, 0, [editOf(b, appended(b))]);
    const { shows } = await newOps(r.bytes);
    // Lines in the paragraph's font; « AJOUT » (capitals the subset lacks) in a substitute: a few more shows.
    expect(shows.length).toBeLessThanOrEqual(b.lines.length + 3);
    const items = await itemsOn(r.bytes, b, 0);
    singleSpaces(items);
    expect(NORM(items.join(""))).toBe(NORM(b.text + " AJOUT"));
    const after = await lookAt(r.bytes);
    const lines = after.lines.filter((l) => l.origin.y > b.rect.y && l.origin.y < b.rect.y + b.rect.h + 2);
    for (const l of lines.slice(0, -1)) expect(Math.abs(l.rect.x + l.rect.w - (b.rect.x + b.rect.w))).toBeLessThan(1.5);
  });

  it("justified text in a 2-byte (CID) font: one TJ per line, single spaces in the extracted text", async () => {
    const { bytes } = await open("pdflib");
    const b = (await blocksOf("pdflib", 1)).find((x) => x.text.startsWith("Ce paragraphe"))!;
    const r = await rewrittenPage(bytes, null, 1, [editOf(b, b.spans!, { align: "justify" })]);
    const items = await itemsOn(r.bytes, b, 0);
    singleSpaces(items);
    expect(NORM(items.join(""))).toBe(NORM(b.text));
    expect((await newOps(r.bytes)).shows.length).toBe(b.lines.length);
    const lines = (await lookAt(r.bytes)).lines.filter(
      (l) => l.origin.y > b.rect.y && l.origin.y < b.rect.y + b.rect.h + 2,
    );
    expect(lines.length).toBe(b.lines.length);
    for (const l of lines.slice(0, -1)) expect(Math.abs(l.rect.x + l.rect.w - (b.rect.x + b.rect.w))).toBeLessThan(1.5);
  });
});
